---
title: "Milestone 2"
author: "Sophie Webster"
date: "2/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Madeleine Snow's Analysis of Tony-Winning Theatre 

As a Broadway aficinado myself (though perhaps not to the degree of Maddie!), I really enjoyed this project. I think the central question was very pertinent to Broadway culture, as plays often seem to be much more ephemeral while musicals can stretch on and on, and it was very smart of Maddie to investigate this in conjuction with Tony status. In her "Summary" plots of plays and musicals, I really appreciate how she explicitly outlined the trends and what they signified. However, I will say that the differing x axis scales on these plots obscured the trends at first and seemed to say the opposite of what the data was actually telling. Also, on both the "Runs of Plays versus Musicals by Year" and "Runs of Award-Nominated versus Award-Winning Shows by Year" graphs, I would have loved to have known which shows each dot represented (arguably, I think that's the most interesting variable). It's a bit harder to go rooting around "Explore the Shows" tab and find exactly what you were looking for. Nonetheless, I really admire Maddie's hard work, as she did significant web scraping to find all the Tony Winners, runtimes, names, and years.

### Michelle Gao: Performance of Political Ads on Google

Michelle's project on political ads was topical and very enlightening. The stacked bar charts were both a telling and eye-catching choice that made it relatively easy to compare candidates -- for example, it was so striking to see Elizabeth Warren's astronomical use of ads from last January to April while others effectively had none. That said, I wish she had included a bit more description or brief analysis of the visible trends because there are so many variables for the viewer to parse. Or I am sure there are so many comments to make on the temporal axis (why one candidate decided to push this many ads right then) that could improve the viewer's experience and strengthen their takeaways. Furthermore, on the "Model" section, I wish there had been more results description that explained the significance value and other commentary (how this challenges or is consistent with current belief, for ex). Nonetheless, there were some really cool take-aways from this project that I'm sure campaign managers would love to know (like that Joe Biden's increased ad-use is actually linked to decreased polling results!).